%undefine _debugsource_packages

Name:           fzf
Version:        0.58.0
Release:        1
Summary:        A command-line fuzzy finder 
License:        MIT
URL:            https://github.com/junegunn/fzf/
Source0:        https://github.com/junegunn/fzf/archive/v%{version}/%{name}-%{version}.tar.gz
# Generated by running, inside the source tree:
# export GOPATH=$(pwd)/.godeps
# go mod download
# tar cJf ../../godeps-for-fzf-0.58.0.tar.xz .godeps
Source1:        godeps-for-fzf-%{version}.tar.xz
BuildRequires:  golang
BuildRequires:  compiler(go-compiler)

%description
It's an interactive filter program for any kind of list; files, command history, processes, hostnames, bookmarks, git commits, etc. 
It implements a "fuzzy" matching algorithm, so you can quickly type in patterns with omitted characters and still get the results you want.
Highlights

    📦 Portable — Distributed as a single binary for easy installation
    ⚡ Blazingly fast — Highly optimized code instantly processes millions of items
    🛠️ Extremely versatile — Fully customizable via an event-action binding mechanism
    🔋 Batteries included — Includes integration with bash, zsh, fish, Vim, and Neovim

%prep
%autosetup -p1 -a1

%build
export GOPATH=$(pwd)/.godeps:$(pwd)/gopath
## Note build takes around 10 minutes, so be patient as there is no output!
go build

%install
export GOPATH=$(pwd)/.godeps:$(pwd)/gopath
%make_install
#install -d -m 0755 %{buildroot}%{_bindir} %{buildroot}%{_datadir}/%{name}
#install -m 0755 %{name} %{buildroot}%{_bindir}/%{name}
#install -m 0644 config/style.css %{buildroot}%{_datadir}/%{name}/style.css

%files
%license LICENSE
